services:
  - type: web
    name: expensetracker-pro-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    healthCheckPath: "/health"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
