name: API CI

on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
      - ".github/workflows/api-ci.yml"
  pull_request:
    paths:
      - "server/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ secrets.PY_VERSION || '3.10' }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # dev tools (optional)
          pip install pytest flake8

      - name: Lint
        run: |
          flake8 . || true  # don’t fail build if you’re still cleaning up

      - name: Run tests
        run: |
          pytest -q || true  # set to plain 'pytest -q' once you have tests
